### ISSUE TITLE
Immediate ServerWide crash.

### ISSUE THREAD

**Issue by JackiTacki** [exaskye/Drogtor#15]
Crashes occur upon player death.

java.lang.NoSuchMethodError: 'void net.minecraft.class_2703.<init>(net.minecraft.class_2703$class_5893, net.minecraft.class_3222[])'
	at net.minecraft.class_1657.drogtor$updatePlayerListEntries(class_1657.java:2441)
	at net.minecraft.class_1657.drogtor$setNickname(class_1657.java:2426)
	at net.minecraft.class_3222.handler$zbj000$copyFrom(class_3222.java:2818)
	at net.minecraft.class_3222.method_14203(class_3222.java)
	at net.minecraft.class_3324.method_14556(class_3324.java:492)
	at net.minecraft.class_3244.method_12068(class_3244.java:1635)
	at net.minecraft.class_2799.method_12120(class_2799.java:24)
	at net.minecraft.class_2799.method_11054(class_2799.java:6)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:787)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:166)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:769)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:763)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:680)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by exaskye** [comment]
1.19.3 is not supported.
